/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menu;
import java.awt.Color;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
/**
 *
 * @author Nitro 5
 */
public class AdminBaru extends javax.swing.JFrame {
    private Connection koneksi; 
    private Statement state;
    /**
     * Creates new form NewJFrame
     */
    public AdminBaru() {
        initComponents();
        setLocationRelativeTo(null);
        //this.setBackground(new Color(0,0,0,0));
       // jPanel1.setBackground(new Color(0,0,0,0));
       // back.setBackground(new Color(0,0,0,0));
       // clear.setBackground(new Color(0,0,0,0));
       // simpan.setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        back = new javax.swing.JButton();
        nm = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        nh = new javax.swing.JLabel();
        nohp = new javax.swing.JTextField();
        uname = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jbt = new javax.swing.JLabel();
        jabatanbox = new javax.swing.JComboBox<>();
        pwtext = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        retyp = new javax.swing.JLabel();
        password1 = new javax.swing.JPasswordField();
        jlabel1 = new javax.swing.JLabel();
        clear = new javax.swing.JButton();
        simpan = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 630));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back.setBackground(new java.awt.Color(255, 255, 255));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Exit Logo.png"))); // NOI18N
        back.setBorder(null);
        back.setBorderPainted(false);
        back.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        back.setOpaque(false);
        back.setPreferredSize(new java.awt.Dimension(137, 50));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 40, 40));

        nm.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        nm.setText("Nama");
        nm.setToolTipText("");
        jPanel1.add(nm, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        nama.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 220, 50));

        nh.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        nh.setText("Nomor Handphone");
        nh.setToolTipText("");
        jPanel1.add(nh, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        nohp.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        nohp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nohpActionPerformed(evt);
            }
        });
        jPanel1.add(nohp, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 220, 50));

        uname.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        uname.setText("Username");
        uname.setToolTipText("");
        jPanel1.add(uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, 20));

        username.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 220, 50));

        jbt.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jbt.setText("Jabatan");
        jbt.setToolTipText("");
        jPanel1.add(jbt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, -1, -1));

        jabatanbox.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jabatanbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Montir" }));
        jPanel1.add(jabatanbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 180, 40));

        pwtext.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        pwtext.setText("Password");
        pwtext.setToolTipText("");
        jPanel1.add(pwtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, -1, -1));

        password.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 225, 30));

        retyp.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        retyp.setText("Re-type Password");
        jPanel1.add(retyp, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 134, 22));

        password1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(password1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, 225, 30));

        jlabel1.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(jlabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, 225, 20));

        clear.setBackground(new java.awt.Color(215, 0, 0));
        clear.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        clear.setText("CLEAR");
        clear.setToolTipText("");
        clear.setBorder(null);
        clear.setBorderPainted(false);
        clear.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel1.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, 130, 60));

        simpan.setBackground(new java.awt.Color(0, 215, 179));
        simpan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        simpan.setText("SAVE");
        simpan.setToolTipText("");
        simpan.setBorder(null);
        simpan.setBorderPainted(false);
        simpan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        jPanel1.add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 480, 130, 60));
        jPanel1.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 550));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
    this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
       nama.setText("");
        nohp.setText("");
        username.setText("");
        password.setText("");
        password1.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void nohpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nohpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nohpActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
        if(password.getText().equals(password1.getText())){
            try {
                Class.forName("com.mysql.jdbc.Driver");
                koneksi = DriverManager.getConnection("jdbc:mysql://localhost/bengkelmms", "root", "");
                state = koneksi.createStatement();
                state.executeUpdate("insert into informasikaryawan values ('"+username.getText()+"','"+nama.getText()+"','"+nohp.getText()+"','"+jabatanbox.getSelectedItem()+"')");
                state.executeUpdate("insert into admin values ('"+username.getText()+"','"+password.getText()+"')");
                state.executeUpdate("insert into statusmontir values ('"+nama.getText()+"','Tersedia')");
                JOptionPane.showMessageDialog(null, "Data berhasil di input.");
                nama.setText("");
                nohp.setText("");
                username.setText("");
                password.setText("");
                password1.setText("");
            }
            catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Data gagal di input."+ e);
            }
        } else {
            jlabel1.setText("Password tidak match");
        }
    }//GEN-LAST:event_simpanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminBaru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminBaru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminBaru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminBaru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminBaru().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel bg;
    private javax.swing.JButton clear;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jabatanbox;
    private javax.swing.JLabel jbt;
    private javax.swing.JLabel jlabel1;
    private javax.swing.JTextField nama;
    private javax.swing.JLabel nh;
    private javax.swing.JLabel nm;
    private javax.swing.JTextField nohp;
    private javax.swing.JPasswordField password;
    private javax.swing.JPasswordField password1;
    private javax.swing.JLabel pwtext;
    private javax.swing.JLabel retyp;
    private javax.swing.JButton simpan;
    private javax.swing.JLabel uname;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
