package menu;
import java.awt.Color;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.DriverManager;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import javax.swing.JOptionPane;
import java.util.Date;
import java.awt.*;
import java.util.HashMap;
import java.util.Locale;
import javax.swing.*;
/**
 *
 * @author KELOMPOK KKP JORDAN
 */
public class Admin extends javax.swing.JFrame {
    private Connection koneksi; 
    private Statement state;
    private ResultSet rs;
    private DefaultTableModel model;
    private void tanggal(){
    Date date = new Date();
    waktu.setText(date.toString());
    waktu.setForeground(new Color(255,255,255));
    }
    private void tampiltable() { 
        model = new DefaultTableModel();
        // Memberi nama pada setiap kolom tabel
        model.addColumn("ID Barang");
        model.addColumn("Nama Barang");
        model.addColumn("Jumlah Barang");
     
    try{
        Class.forName("com.mysql.jdbc.Driver");
        koneksi = DriverManager.getConnection("jdbc:mysql://localhost/bengkelmms", "root", "");
        state   = koneksi.createStatement();
        rs      = state.executeQuery("SELECT * from barang ORDER BY qty");
        
    while (rs.next()) {
        model.addRow(new Object[]{
         rs.getString("idbarang"),
         rs.getString("namabarang"),
         rs.getString("qty")
                 });}
    listsiswa.setModel(model);
    
    } catch (Exception e){
        }
    }
    private void tampiltable2() { 
        model = new DefaultTableModel();
        // Memberi nama pada setiap kolom tabel
        model.addColumn("Nama Montir");
        model.addColumn("Status Kerja");
     
    try{
        Class.forName("com.mysql.jdbc.Driver");
        koneksi = DriverManager.getConnection("jdbc:mysql://localhost/bengkelmms", "root", "");
        state   = koneksi.createStatement();
        rs      = state.executeQuery("SELECT * from statusmontir ORDER BY nama");
        
    while (rs.next()) {
        model.addRow(new Object[]{
         rs.getString("nama"),
         rs.getString("status")
                 });}
    tablemontir.setModel(model);
    
    } catch (Exception e){
        }
    }
    
    private void cleantable(){
        int baris = model.getRowCount();
        for(int a=0;a<baris;a++)
        {
            model.removeRow(0);
        }
        
    }
    public Admin() {
        initComponents();
        tanggal();
        panelsetting.setEnabled(false);
        panelsetting.setVisible(false);
        closet.setEnabled(false);
        closet.setVisible(false);

        
        panelmontir.setVisible(false);
        panelmontir.setEnabled(false);
        panelcari.setVisible(false);
        panelcari.setEnabled(false);
        panelreport.setVisible(false);
        panelreport.setEnabled(false);
        panelorderan.setVisible(true);
        panelorderan.setEnabled(true);
        
       /*order.setBackground(new Color(0,0,0,0));
       stokbarang.setBackground(new Color(0,0,0,0));
       montir.setBackground(new Color(0,0,0,0));
       report.setBackground(new Color(0,0,0,0));*/
       
       /*reportstok.setText("REPORT REGIONAL JAKARTA");
        reportstok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportstokMouseClicked(evt);
            }
        });
        getContentPane().add(reportstok, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0));*/
       //jLabel4.setBackground(new Color(215,0,0));
       
        setLocationRelativeTo(null);
        tampiltable();
        tampiltable2();
        Locale locale = new Locale ("id", "ID");
        Locale.setDefault(locale);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgmenu = new javax.swing.JLabel();
        bgputih3 = new javax.swing.JLabel();
        bgformkanan = new javax.swing.JLabel();
        mainpanel = new javax.swing.JPanel();
        menupanel = new javax.swing.JPanel();
        panelorderan = new javax.swing.JPanel();
        exit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panelcari = new javax.swing.JPanel();
        exit1 = new javax.swing.JButton();
        nourut = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        listsiswa = new javax.swing.JTable();
        msknmbrgkdbrg = new javax.swing.JLabel();
        refresh = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelmontir = new javax.swing.JPanel();
        exit2 = new javax.swing.JButton();
        tambah = new javax.swing.JLabel();
        hapus = new javax.swing.JLabel();
        ID = new javax.swing.JLabel();
        namamontir = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablemontir = new javax.swing.JTable();
        panelreport = new javax.swing.JPanel();
        exit3 = new javax.swing.JButton();
        pemjasa = new javax.swing.JLabel();
        reportstok = new javax.swing.JLabel();
        trxharian = new javax.swing.JLabel();
        pembarang = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        report = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        montir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        stokbarang = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        order = new javax.swing.JButton();
        closet = new javax.swing.JLabel();
        opset = new javax.swing.JLabel();
        panelsetting = new javax.swing.JPanel();
        logout = new javax.swing.JLabel();
        infoadmin = new javax.swing.JLabel();
        waktu = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        bgmenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bgmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sidebar.png"))); // NOI18N

        bgputih3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bg-menu.png"))); // NOI18N

        bgformkanan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bgformkanan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bg-menu.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1080, 720));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainpanel.setBackground(new java.awt.Color(215, 0, 0));
        mainpanel.setPreferredSize(new java.awt.Dimension(1080, 720));
        mainpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menupanel.setLayout(new java.awt.CardLayout());

        panelorderan.setBackground(new java.awt.Color(255, 255, 255));
        panelorderan.setPreferredSize(new java.awt.Dimension(100, 100));
        panelorderan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Exit Logo.png"))); // NOI18N
        exit.setBorder(null);
        exit.setBorderPainted(false);
        exit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        panelorderan.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 40, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ord-jasa.png"))); // NOI18N
        jLabel3.setOpaque(true);
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        panelorderan.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 182, 400));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pemb-brg.png"))); // NOI18N
        jLabel4.setOpaque(true);
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        panelorderan.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 182, 400));

        menupanel.add(panelorderan, "card2");

        panelcari.setBackground(new java.awt.Color(255, 255, 255));
        panelcari.setMinimumSize(new java.awt.Dimension(1080, 720));
        panelcari.setPreferredSize(new java.awt.Dimension(100, 100));
        panelcari.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Exit Logo.png"))); // NOI18N
        exit1.setBorder(null);
        exit1.setBorderPainted(false);
        exit1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit1ActionPerformed(evt);
            }
        });
        panelcari.add(exit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 40, -1, -1));

        nourut.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nourut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nourut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nourutActionPerformed(evt);
            }
        });
        nourut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nourutKeyReleased(evt);
            }
        });
        panelcari.add(nourut, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 120, 30));

        listsiswa.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        listsiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        listsiswa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        listsiswa.setEnabled(false);
        listsiswa.setGridColor(new java.awt.Color(153, 204, 255));
        listsiswa.setOpaque(false);
        listsiswa.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(listsiswa);

        panelcari.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 700, 480));

        msknmbrgkdbrg.setFont(new java.awt.Font("Poppins SemiBold", 1, 13)); // NOI18N
        msknmbrgkdbrg.setText("Masukan nama barang / kode barang :");
        panelcari.add(msknmbrgkdbrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        refresh.setBackground(new java.awt.Color(0, 149, 215));
        refresh.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        refresh.setText("REFRESH");
        refresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshMouseClicked(evt);
            }
        });
        panelcari.add(refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 184, 50, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("TAMBAH BARANG");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        panelcari.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 74, 180, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("UPDATE STOK BARANG");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        panelcari.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 210, 40));

        menupanel.add(panelcari, "card5");

        panelmontir.setBackground(new java.awt.Color(255, 255, 255));
        panelmontir.setMinimumSize(new java.awt.Dimension(1080, 720));
        panelmontir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Exit Logo.png"))); // NOI18N
        exit2.setBorder(null);
        exit2.setBorderPainted(false);
        exit2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit2ActionPerformed(evt);
            }
        });
        panelmontir.add(exit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 40, -1, -1));

        tambah.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tambah.setText("TAMBAH KARYAWAN");
        tambah.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tambahMouseClicked(evt);
            }
        });
        panelmontir.add(tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 200, 30));

        hapus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        hapus.setText("UPDATE STATUS");
        hapus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        hapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hapusMouseClicked(evt);
            }
        });
        panelmontir.add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 200, 30));

        ID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ID.setText("NAMA:");
        panelmontir.add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 70, 30));

        namamontir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        namamontir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                namamontirKeyReleased(evt);
            }
        });
        panelmontir.add(namamontir, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 120, -1));

        tablemontir.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tablemontir);

        panelmontir.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, 220));

        menupanel.add(panelmontir, "card3");

        panelreport.setBackground(new java.awt.Color(255, 255, 255));
        panelreport.setPreferredSize(new java.awt.Dimension(1080, 720));
        panelreport.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Exit Logo.png"))); // NOI18N
        exit3.setBorder(null);
        exit3.setBorderPainted(false);
        exit3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit3ActionPerformed(evt);
            }
        });
        panelreport.add(exit3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 40, -1, -1));

        pemjasa.setBackground(new java.awt.Color(255, 255, 255));
        pemjasa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pemjasa.png"))); // NOI18N
        pemjasa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pemjasaMouseClicked(evt);
            }
        });
        panelreport.add(pemjasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, -1, -1));

        reportstok.setBackground(new java.awt.Color(255, 255, 255));
        reportstok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/stokbarang.png"))); // NOI18N
        reportstok.setOpaque(true);
        reportstok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportstokMouseClicked(evt);
            }
        });
        reportstok.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                reportstokKeyPressed(evt);
            }
        });
        panelreport.add(reportstok, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 216, 216));

        trxharian.setBackground(new java.awt.Color(255, 255, 255));
        trxharian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/trxharian.png"))); // NOI18N
        trxharian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                trxharianMouseClicked(evt);
            }
        });
        panelreport.add(trxharian, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, -1, -1));

        pembarang.setBackground(new java.awt.Color(255, 255, 255));
        pembarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pembarang.png"))); // NOI18N
        pembarang.setOpaque(true);
        pembarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pembarangMouseClicked(evt);
            }
        });
        panelreport.add(pembarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, -1, -1));

        menupanel.add(panelreport, "card3");

        mainpanel.add(menupanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 0, -1, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        report.setBackground(new java.awt.Color(255, 255, 255));
        report.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        report.setText("LAPORAN");
        report.setBorder(null);
        report.setBorderPainted(false);
        report.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportActionPerformed(evt);
            }
        });
        jPanel4.add(report, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        mainpanel.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 300, 40));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        montir.setBackground(new java.awt.Color(255, 255, 255));
        montir.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        montir.setText("TABEL MONTIR");
        montir.setBorder(null);
        montir.setBorderPainted(false);
        montir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        montir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                montirActionPerformed(evt);
            }
        });
        jPanel3.add(montir, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        mainpanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 300, 40));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        stokbarang.setBackground(new java.awt.Color(255, 255, 255));
        stokbarang.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        stokbarang.setText("STOK BARANG");
        stokbarang.setBorder(null);
        stokbarang.setBorderPainted(false);
        stokbarang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        stokbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stokbarangActionPerformed(evt);
            }
        });
        jPanel2.add(stokbarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        mainpanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 300, 40));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        order.setBackground(new java.awt.Color(255, 255, 255));
        order.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        order.setText("NEW ORDER");
        order.setBorder(null);
        order.setBorderPainted(false);
        order.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderActionPerformed(evt);
            }
        });
        jPanel1.add(order, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        mainpanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 300, 40));

        closet.setBackground(new java.awt.Color(0, 0, 0));
        closet.setForeground(new java.awt.Color(255, 255, 255));
        closet.setText("SETTINGS");
        closet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closetMouseClicked(evt);
            }
        });
        mainpanel.add(closet, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 640, 90, 70));

        opset.setForeground(new java.awt.Color(255, 255, 255));
        opset.setText("SETTINGS");
        opset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                opsetMouseClicked(evt);
            }
        });
        mainpanel.add(opset, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 640, 90, 70));

        panelsetting.setBackground(new java.awt.Color(255, 255, 255));
        panelsetting.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logout.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        logout.setText("LOGOUT");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        panelsetting.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 100, 30));

        infoadmin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        infoadmin.setText("INFO");
        infoadmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                infoadminMouseClicked(evt);
            }
        });
        panelsetting.add(infoadmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 90, 30));

        mainpanel.add(panelsetting, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 610, 140, 100));

        waktu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mainpanel.add(waktu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 290, 20));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/download (1).png"))); // NOI18N
        mainpanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, 90));

        getContentPane().add(mainpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nourutKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nourutKeyReleased
    tampiltable();
        cleantable();
    
    try{
        Class.forName("com.mysql.jdbc.Driver");
        koneksi = DriverManager.getConnection("jdbc:mysql://localhost/bengkelmms", "root", "");
        state   = koneksi.createStatement();
        rs      = state.executeQuery("SELECT * from barang where idbarang like '%"+nourut.getText()+"%' or namabarang like '%"+nourut.getText()+"%' ORDER BY qty");
        
    while (rs.next()) {
        model.addRow(new Object[]{
         rs.getString("idbarang"),
         rs.getString("namabarang"),
         rs.getString("qty")
                 });}
    listsiswa.setModel(model);
    
    } catch (Exception e){
        }
    }//GEN-LAST:event_nourutKeyReleased

    private void nourutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nourutActionPerformed

    }//GEN-LAST:event_nourutActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);        
    }//GEN-LAST:event_exitActionPerformed

    private void infoadminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoadminMouseClicked
        AdminLogin al = new AdminLogin();
        al.setVisible(true);
        al.pack();
        al.setDefaultCloseOperation(Login.EXIT_ON_CLOSE);
    }//GEN-LAST:event_infoadminMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        Login lg = new Login();
        lg.setVisible(true);
        lg.pack();
        lg.setDefaultCloseOperation(Login.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_logoutMouseClicked

    private void opsetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opsetMouseClicked
        opset.setEnabled(false);
        opset.setVisible(false);
        panelsetting.setEnabled(true);
        panelsetting.setVisible(true);
        closet.setEnabled(true);
        closet.setVisible(true);
    }//GEN-LAST:event_opsetMouseClicked

    private void closetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closetMouseClicked
        closet.setEnabled(false);
        closet.setVisible(false);
        panelsetting.setEnabled(false);
        panelsetting.setVisible(false);
        opset.setEnabled(true);
        opset.setVisible(true);
    }//GEN-LAST:event_closetMouseClicked

    private void reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportActionPerformed
        panelreport.setVisible(true);
        panelreport.setEnabled(true);
        panelorderan.setVisible(false);
        panelorderan.setEnabled(false);
        panelmontir.setVisible(false);
        panelmontir.setEnabled(false);
        panelcari.setVisible(false);
        panelcari.setEnabled(false);
        
    }//GEN-LAST:event_reportActionPerformed

    private void montirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_montirActionPerformed
        panelmontir.setVisible(true);
        panelmontir.setEnabled(true);
        panelorderan.setVisible(false);
        panelorderan.setEnabled(false);
        panelcari.setVisible(false);
        panelcari.setEnabled(false);
        panelreport.setVisible(false);
        panelreport.setEnabled(false);
    }//GEN-LAST:event_montirActionPerformed

    private void stokbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stokbarangActionPerformed
        panelcari.setVisible(true);
        panelcari.setEnabled(true);
        panelorderan.setVisible(false);
        panelorderan.setEnabled(false);
        panelmontir.setVisible(false);
        panelmontir.setEnabled(false);
        panelreport.setVisible(false);
        panelreport.setEnabled(false);
    }//GEN-LAST:event_stokbarangActionPerformed

    private void exit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit1ActionPerformed
        System.exit(0); 
    }//GEN-LAST:event_exit1ActionPerformed

    private void exit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit2ActionPerformed
        System.exit(0); 
    }//GEN-LAST:event_exit2ActionPerformed

    private void exit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit3ActionPerformed
        System.exit(0); 
    }//GEN-LAST:event_exit3ActionPerformed

    private void orderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderActionPerformed
        panelorderan.setVisible(true);
        panelorderan.setEnabled(true);
        panelcari.setVisible(false);
        panelcari.setEnabled(false);
        panelmontir.setVisible(false);
        panelmontir.setEnabled(false);
        panelreport.setVisible(false);
        panelreport.setEnabled(false);
        
    }//GEN-LAST:event_orderActionPerformed

    private void refreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshMouseClicked
        tampiltable();
        // TODO add your handling code here:
    }//GEN-LAST:event_refreshMouseClicked

    private void namamontirKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_namamontirKeyReleased
        tampiltable2();
        cleantable();
    
    try{
        Class.forName("com.mysql.jdbc.Driver");
        koneksi = DriverManager.getConnection("jdbc:mysql://localhost/bengkelmms", "root", "");
        state   = koneksi.createStatement();
        rs      = state.executeQuery("SELECT * from informasikaryawan where nama like '%"+namamontir.getText()+"%' ORDER BY nama");
        
    while (rs.next()) {
        model.addRow(new Object[]{
         rs.getString("nama"),
         rs.getString("status")
                 });}
    tablemontir.setModel(model);
    
    } catch (Exception e){
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_namamontirKeyReleased

    private void tambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tambahMouseClicked
        AdminBaru ab = new AdminBaru();
        ab.setVisible(true);
        ab.pack();
        ab.setDefaultCloseOperation(Login.EXIT_ON_CLOSE);        // TODO add your handling code here:
    }//GEN-LAST:event_tambahMouseClicked

    private void hapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hapusMouseClicked
        updatestatus us = new updatestatus();
        us.setVisible(true);
        us.pack();
        us.setDefaultCloseOperation(Login.EXIT_ON_CLOSE);        // TODO add your handling code here:
    }//GEN-LAST:event_hapusMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        orderjasa oj = new orderjasa();
        oj.setVisible(true);
        oj.pack();
        oj.setDefaultCloseOperation(Login.EXIT_ON_CLOSE);       // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        orderbarang ob = new orderbarang();
        ob.setVisible(true);
        ob.pack();
        ob.setDefaultCloseOperation(Login.EXIT_ON_CLOSE);         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        updatestok ok = new updatestok();
        ok.setVisible(true);
        ok.pack();
        ok.setDefaultCloseOperation(Login.EXIT_ON_CLOSE);         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        NewItem ni = new NewItem();
        ni.setVisible(true);
        ni.pack();
        ni.setDefaultCloseOperation(Login.EXIT_ON_CLOSE);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void reportstokKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_reportstokKeyPressed

    }//GEN-LAST:event_reportstokKeyPressed

    private void reportstokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportstokMouseClicked
        try {
            JasperPrint jp = JasperFillManager.fillReport(getClass().getResourceAsStream("stokbarang.jasper"), null, Koneksi.getConnection());
            JasperViewer.viewReport(jp, false);
        }catch(Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }  
    }//GEN-LAST:event_reportstokMouseClicked

    private void pembarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pembarangMouseClicked
        try {  
            JasperPrint jp = JasperFillManager.fillReport(getClass().getResourceAsStream("pemesananbarang.jasper"), null, Koneksi.getConnection());
            JasperViewer.viewReport(jp, false);
        }catch(Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }  
    }//GEN-LAST:event_pembarangMouseClicked

    private void pemjasaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pemjasaMouseClicked
        try {
            JasperPrint jp = JasperFillManager.fillReport(getClass().getResourceAsStream("pemesananjasa.jasper"), null, Koneksi.getConnection());
            JasperViewer.viewReport(jp, false);
        }catch(Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_pemjasaMouseClicked

    private void trxharianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trxharianMouseClicked
        try {
            JasperPrint jp = JasperFillManager.fillReport(getClass().getResourceAsStream("trxharian.jasper"), null, Koneksi.getConnection());
            JasperViewer.viewReport(jp, false);
        }catch(Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_trxharianMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ID;
    private javax.swing.JLabel bgformkanan;
    private javax.swing.JLabel bgmenu;
    private javax.swing.JLabel bgputih3;
    private javax.swing.JLabel closet;
    private javax.swing.JButton exit;
    private javax.swing.JButton exit1;
    private javax.swing.JButton exit2;
    private javax.swing.JButton exit3;
    private javax.swing.JLabel hapus;
    private javax.swing.JLabel infoadmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable listsiswa;
    private javax.swing.JLabel logout;
    private javax.swing.JPanel mainpanel;
    private javax.swing.JPanel menupanel;
    private javax.swing.JButton montir;
    private javax.swing.JLabel msknmbrgkdbrg;
    private javax.swing.JTextField namamontir;
    private javax.swing.JTextField nourut;
    private javax.swing.JLabel opset;
    private javax.swing.JButton order;
    private javax.swing.JPanel panelcari;
    private javax.swing.JPanel panelmontir;
    private javax.swing.JPanel panelorderan;
    private javax.swing.JPanel panelreport;
    private javax.swing.JPanel panelsetting;
    private javax.swing.JLabel pembarang;
    private javax.swing.JLabel pemjasa;
    private javax.swing.JLabel refresh;
    private javax.swing.JButton report;
    private javax.swing.JLabel reportstok;
    private javax.swing.JButton stokbarang;
    private javax.swing.JTable tablemontir;
    private javax.swing.JLabel tambah;
    private javax.swing.JLabel trxharian;
    private javax.swing.JLabel waktu;
    // End of variables declaration//GEN-END:variables
}
