/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menu;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
/**
 *
 * @author Strellizya
 */
public class NewItem extends javax.swing.JFrame {
    private Connection koneksi; 
    private Statement state;
    /**
     * Creates new form NewItem
     */
    public NewItem() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        idbar = new javax.swing.JLabel();
        nmbrg = new javax.swing.JLabel();
        jmb = new javax.swing.JLabel();
        hrgb = new javax.swing.JLabel();
        idb = new javax.swing.JTextField();
        namab = new javax.swing.JTextField();
        jmh = new javax.swing.JTextField();
        hgb = new javax.swing.JTextField();
        clear = new javax.swing.JButton();
        save = new javax.swing.JButton();
        exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        idbar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        idbar.setText("ID BARANG");
        jPanel1.add(idbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, -1, -1));

        nmbrg.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nmbrg.setText("NAMA BARANG");
        jPanel1.add(nmbrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, -1, -1));

        jmb.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jmb.setText("JUMLAH BARANG");
        jPanel1.add(jmb, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, 30));

        hrgb.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        hrgb.setText("HARGA BARANG");
        jPanel1.add(hrgb, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, -1, 30));

        idb.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        idb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idbActionPerformed(evt);
            }
        });
        jPanel1.add(idb, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 90, -1));

        namab.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        namab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namabActionPerformed(evt);
            }
        });
        jPanel1.add(namab, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 300, -1));

        jmh.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jmh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmhActionPerformed(evt);
            }
        });
        jPanel1.add(jmh, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 90, 30));

        hgb.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        hgb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hgbActionPerformed(evt);
            }
        });
        jPanel1.add(hgb, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 170, 30));

        clear.setBackground(new java.awt.Color(0, 149, 215));
        clear.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        clear.setText("CLEAR");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel1.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 110, 50));

        save.setBackground(new java.awt.Color(0, 215, 179));
        save.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        save.setText("SAVE");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel1.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, 110, 50));

        exit.setBackground(new java.awt.Color(255, 255, 255));
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Exit Logo.png"))); // NOI18N
        exit.setBorder(null);
        exit.setBorderPainted(false);
        exit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exit.setOpaque(false);
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namabActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_exitActionPerformed

    private void idbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idbActionPerformed

    private void jmhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmhActionPerformed

    private void hgbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hgbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hgbActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        idb.setText("");
        namab.setText("");
        jmh.setText("");
        hgb.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
    try {
                Class.forName("com.mysql.jdbc.Driver");
                koneksi = DriverManager.getConnection("jdbc:mysql://localhost/bengkelmms", "root", "");
                state = koneksi.createStatement();
                state.executeUpdate("insert into barang values ('"+idb.getText()+"','"+namab.getText()+"','"+jmh.getText()+"','"+hgb.getText()+"')");
                JOptionPane.showMessageDialog(null, "Barang berhasil ditambahkan");
            }
            catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Data gagal di input."+ e);
            }        // TODO add your handling code here:
    }//GEN-LAST:event_saveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewItem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clear;
    private javax.swing.JButton exit;
    private javax.swing.JTextField hgb;
    private javax.swing.JLabel hrgb;
    private javax.swing.JTextField idb;
    private javax.swing.JLabel idbar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jmb;
    private javax.swing.JTextField jmh;
    private javax.swing.JTextField namab;
    private javax.swing.JLabel nmbrg;
    private javax.swing.JButton save;
    // End of variables declaration//GEN-END:variables
}
