/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menu;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.DriverManager;
import javax.swing.JOptionPane;

/**
 *
 * @author Strellizya
 */
public class updatestatus extends javax.swing.JFrame {
    private Connection koneksi; 
    private Statement state;
    private ResultSet   rs;
    /**
     * Creates new form updatestatus
     */
    private void tampilbox() {
        namamontir.setSelectedItem(1);
     try{
        Class.forName("com.mysql.jdbc.Driver");
        koneksi = DriverManager.getConnection("jdbc:mysql://localhost/bengkelmms", "root", "");
        state   = koneksi.createStatement();
        rs      = state.executeQuery("SELECT nama from statusmontir ORDER BY nama");
        
    while (rs.next()) {
        namamontir.addItem(rs.getString("nama"));
    }
    rs.last();int jumlahdata = rs.getRow(); rs.first();
    } catch (Exception e){
        }
    }

    public updatestatus() {
        initComponents();
        tampilbox();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nama = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        namamontir = new javax.swing.JComboBox<>();
        statuskerja = new javax.swing.JComboBox<>();
        buttonupdate = new javax.swing.JButton();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nama.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nama.setText("NAMA");
        jPanel1.add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        status.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        status.setText("STATUS");
        jPanel1.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, -1, -1));

        namamontir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        namamontir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namamontirActionPerformed(evt);
            }
        });
        jPanel1.add(namamontir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        statuskerja.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        statuskerja.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tersedia", "Tidak Tersedia" }));
        statuskerja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statuskerjaActionPerformed(evt);
            }
        });
        jPanel1.add(statuskerja, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, -1, -1));

        buttonupdate.setBackground(new java.awt.Color(215, 0, 0));
        buttonupdate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonupdate.setText("UPDATE");
        buttonupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonupdateActionPerformed(evt);
            }
        });
        jPanel1.add(buttonupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, -1, -1));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Exit Logo.png"))); // NOI18N
        back.setBorder(null);
        back.setBorderPainted(false);
        back.setOpaque(false);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 40, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void statuskerjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statuskerjaActionPerformed
    
// TODO add your handling code here:
    }//GEN-LAST:event_statuskerjaActionPerformed

    private void buttonupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonupdateActionPerformed
        try {
            Class.forName("com.mysql.jdbc.Driver");
            koneksi = DriverManager.getConnection("jdbc:mysql://localhost/bengkelmms", "root", "");
            state = koneksi.createStatement();
            state.executeUpdate("update statusmontir set status='"+statuskerja.getSelectedItem()+"'where nama ='"+namamontir.getSelectedItem()+"'");
            JOptionPane.showMessageDialog(null, "STATUS BERHASIL DIPERBAHARUI");
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "GAGAL!"+ e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonupdateActionPerformed

    private void namamontirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namamontirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namamontirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updatestatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updatestatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updatestatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updatestatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updatestatus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton buttonupdate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nama;
    private javax.swing.JComboBox<String> namamontir;
    private javax.swing.JLabel status;
    private javax.swing.JComboBox<String> statuskerja;
    // End of variables declaration//GEN-END:variables
}
